### ISSUE TITLE
Add browserify to package.json

### ISSUE THREAD

**Issue by muxahuk** [lsphillips/Crumble#1]
Hello guys,

Using browserify with babelify in my gulpfile
Issue appears when i'm trying to uglify the pipe line
As you'r plugin is not transformed automatically.

Adding "browserify" settings in package.json would be nice!
The error is "unexpected (const)"

```
"browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "es2015"
          ]
        }
      ]
    ]
}
```

**Comment by lsphillips** [comment]
Closing as this should no longer be an issue.

`v2.2.0` introduced a browser entry point that is ES5 compatible and minified. Bundlers like `browserify`, `rollup` and `webpack` should support this.
